export const DARKGAMMON_COPY = {
  brand: {
    name: "Darkgammon",
    tagline: "Choose your side. Roll the dice. Claim the board.",
    description:
      "A real-time backgammon battle between Light and Dark. Challenge an opponent, replay the match, and export the battle as a video.",
    title: "Darkgammon — Light vs Dark",
    edition: "June Solstice Edition",
    supportCopy: "Light and Dark meet across the board.",
    motto: "Choose your side.",
    endMotto: "THE BATTLE ENDS\nTHE CYCLE CONTINUES",
  },
  sides: {
    white: "Light",
    black: "Dark",
  },
  connection: {
    lost: "Connection lost",
    restored: "Connection restored",
    joined: (name: string) => `${name} joined the battle`,
    left: (name: string) => `${name} left the battle`,
    connected: "Connected",
    disconnected: "Disconnected",
    waiting: "Waiting",
    reconnecting: "Reconnecting",
  },
  battle: {
    create: "Create a Battle",
    join: "Join the Battle",
    waiting: "Waiting for an opponent",
    summon: "Summon an Opponent",
    shareLink: "Share Battle Link",
    linkCopied: "Battle link copied",
    scanToJoin: "Scan to join the battle",
    full: "This battle already has two sides",
    notFound: "Battle not found",
    leavePromptTitle: "Leave the Battle?",
    leavePromptDesc: "Leaving now may end the battle for your side.",
    cancel: "Cancel",
    leave: "Leave Battle",
    surrenderPromptTitle: "Surrender?",
    surrenderPromptDesc: "The opposing side will be declared victorious.",
    keepFighting: "Keep Fighting",
    surrender: "Surrender",
    watchReplay: "Watch Replay",
    exportVideo: "Export Battle Video",
    challengeAgain: "Challenge Again",
    returnHome: "Return Home",
    replayHeading: "BATTLE REPLAY",
    replaySubtitle: "Every move leaves a trace.",
    replayLoading: "Restoring the battle…",
    replaySpeed: "Replay Speed",
    previousMove: "Previous Move",
    nextMove: "Next Move",
    restart: "Restart",
    turn: "Turn",
    videoForging: "Forging your battle replay…",
    videoReady: "Your battle replay is ready.",
    videoFailed: "The battle replay could not be created.",
    downloadAgain: "Download Again",
    playReplay: "Play Replay",
    pause: "Pause",
  },
  inGame: {
    rollDice: "Roll Dice",
    yourTurn: "Your Turn",
    opponentsTurn: "Opponent's Turn",
    endTurn: "End Turn",
    surrender: "Surrender",
    offerDouble: "Offer Double",
    acceptDouble: "Accept Double",
    declineDouble: "Decline Double",
    leaveBattle: "Leave Battle",
    unmute: "Unmute",
    mute: "Mute",
    boardBalanced: "The board is balanced",
    lightControl: "Light is in control",
    darkControl: "Dark is gaining ground",
    winnerLight: "LIGHT PREVAILS",
    winnerDark: "DARK PREVAILS",
    winnerLightSub: "The longest day belongs to the Light.",
    winnerDarkSub: "Night has claimed the board.",
    victory: "Your side prevails!",
    defeat: "Your side has fallen.",
    gameOverHeading: "THE BATTLE IS OVER",
    victoryResult: "Victory",
    defeatResult: "Defeat",
    resultVictorySub: "Your side prevailed.",
    resultDefeatSub: "Your side has fallen.",
    reasonBearOff: "All checkers borne off",
    reasonResignation: "Victory by surrender",
    reasonDeclined: "Doubling challenge declined",
    guest: "Wanderer",
  },
  messages: {
    challengeTitle: "Challenge Message",
    challengePlaceholder: "The Dark will fall before sunset.",
  },
  notifications: {
    summonTitle: (name: string) => `${name} is summoning you to a battle!`,
    accepted: (name: string) =>
      `${name} accepted your challenge! The battle begins...`,
    declined: (name: string) => `${name} declined your challenge.`,
  },
} as const;

export function getSideLabel(color: "white" | "black"): "Light" | "Dark" {
  return color === "white" ? "Light" : "Dark";
}
